name: Update iota.rb info
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # update at every day 20:00(utc+8)

jobs:
  update-iota-rb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get package.json
        run: |
          curl -s -A "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:32.0) Gecko/20100101 Firefox/32.0" -H "Accept: application/json" "https://im.gss.com.tw/download/package.json" --resolve im.gss.com.tw:443:60.251.121.232 -O

      - name: Extract version from package.json
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: "jq .app.mac.version package.json -r"

      - name: Extract download path from package.json
        uses: sergeysova/jq-action@v2
        id: downloadPath
        with:
          cmd: "jq .app.mac.url package.json -r"

      - name: Build rb
        run: |
          cat << EOF > ./Casks/iota.rb 
          cask "iota" do
            version "${{ steps.version.outputs.value }}"
            sha256 :no_check

            url "${{ steps.downloadPath.outputs.value }}",
                user_agent: :fake
            name "iota"
            homepage "https://im.gss.com.tw/"

            auto_updates true

            app "iota.app"
          end
          EOF

      - name: Commit files
        run: |
          git config --local user.email "a26007565@gmail.com"
          git config --local user.name "weiting"
          git commit -m "Update iota.rb" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
